<a href="https://colab.research.google.com/github/habiib1999/Face-Recognition/blob/main/Ass1_PR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data read and Split [Abdul rahman Habib]

In [7]:
import numpy as np
import pandas as pd
%matplotlib inline
from matplotlib import pyplot as plt
import cv2
import os, sys

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
BASE = '/content/drive/MyDrive/ssp/8th/ORL_DataSet/'
filepaths = [] # Contains the absolute paths of all the image files
for s_i in os.listdir(BASE): # The folders containing the files are labelled as s1, s2, etc
    if s_i != 'README': # There is also a README file present in the data, this must be ignored
        for filename in os.listdir(BASE + s_i):
            filepaths.append(BASE + s_i + '/' + filename)

In [ ]:
images = []
for filepath in filepaths:
    images.append(cv2.imread(filepath, 0).flatten())
images = np.array(images)

In [ ]:
labels = []
for i in range (40): #40 person
  for j in range(10): #images
    labels.append(i+1)
labels = np.array(labels)
print(labels)


[ 1  1  1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  2  2  2  3  3  3  3
  3  3  3  3  3  3  4  4  4  4  4  4  4  4  4  4  5  5  5  5  5  5  5  5
  5  5  6  6  6  6  6  6  6  6  6  6  7  7  7  7  7  7  7  7  7  7  8  8
  8  8  8  8  8  8  8  8  9  9  9  9  9  9  9  9  9  9 10 10 10 10 10 10
 10 10 10 10 11 11 11 11 11 11 11 11 11 11 12 12 12 12 12 12 12 12 12 12
 13 13 13 13 13 13 13 13 13 13 14 14 14 14 14 14 14 14 14 14 15 15 15 15
 15 15 15 15 15 15 16 16 16 16 16 16 16 16 16 16 17 17 17 17 17 17 17 17
 17 17 18 18 18 18 18 18 18 18 18 18 19 19 19 19 19 19 19 19 19 19 20 20
 20 20 20 20 20 20 20 20 21 21 21 21 21 21 21 21 21 21 22 22 22 22 22 22
 22 22 22 22 23 23 23 23 23 23 23 23 23 23 24 24 24 24 24 24 24 24 24 24
 25 25 25 25 25 25 25 25 25 25 26 26 26 26 26 26 26 26 26 26 27 27 27 27
 27 27 27 27 27 27 28 28 28 28 28 28 28 28 28 28 29 29 29 29 29 29 29 29
 29 29 30 30 30 30 30 30 30 30 30 30 31 31 31 31 31 31 31 31 31 31 32 32
 32 32 32 32 32 32 32 32 33 33 33 33 33 33 33 33 33

In [ ]:
trainData = []
testData = []
trainLabels = []
testLabels = []
count = 0
for image,label in zip(images,labels):
  if count % 2 == 1:
    trainData.append(image)
    trainLabels.append(label)
  else:
    testData.append(image)
    testLabels.append(label)
  count += 1 
trainData = np.array(trainData) 
testData = np.array(testData)
trainLabels = np.array(trainLabels) 
testLabels = np.array(testLabels)

In [ ]:
for image in images:
  print(image)
print("-------------------------------------------------------------------------------------------------")
for trainImg in trainData:
  print(trainImg)
print("-------------------------------------------------------------------------------------------------")

for testImg in testData:
  print(testImg)   

[51 48 43 ... 29 28 32]
[44 48 45 ... 33 36 37]
[48 45 45 ... 28 37 29]
[45 49 47 ... 40 30 44]
[47 47 47 ... 30 35 33]
[52 48 47 ... 32 31 37]
[50 46 49 ... 33 33 41]
[48 44 49 ... 38 35 44]
[47 49 46 ... 31 32 34]
[48 46 49 ... 31 31 36]
[53 52 61 ... 46 45 45]
[52 56 60 ... 39 41 44]
[48 45 50 ... 46 50 53]
[53 58 57 ... 38 47 39]
[49 45 46 ... 43 42 45]
[56 61 54 ... 40 43 45]
[45 52 48 ... 48 43 47]
[52 41 48 ... 44 43 46]
[50 57 56 ... 39 46 43]
[47 43 48 ... 45 49 50]
[111 112 110 ...  21  20  17]
[110 106 106 ...  19  21  19]
[108 109 110 ...  24  23  30]
[110 110 112 ...  20  31  16]
[105 110 106 ...  18  27  22]
[113 110 110 ...  21  21  20]
[108 111 110 ...  53  48  56]
[106 109 105 ...  35  45  48]
[108 112 110 ...  22  30  20]
[104 105 102 ...  20  28  34]
[46 45 49 ... 56 60 58]
[63 54 58 ... 63 63 64]
[ 72  73  77 ... 100  86  76]
[41 43 43 ... 45 47 46]
[61 62 64 ... 51 55 53]
[63 60 63 ... 63 69 58]
[59 60 59 ... 55 53 56]
[ 69  76  69 ... 104 121  93]
[60 57 59 ... 49

# LDA [Mohammed Aiman]

In [ ]:

#calculate over all mean
mu = np.mean(trainData,axis=0)
print(mu)

[86.    85.535 86.005 ... 76.92  75.79  76.27 ]


In [ ]:
#calculate over all mean
#seperate each class and copmute each mean 

#seperate each class and copmute each mean 
classes_k = [] #2d arrray 40p*5i
mean_k = [] #2d arrray 40p*1

for i in range (0,200,5): #40 person
  class_n = trainData[i:i+5, :]
  classes_k.append(class_n)
  mean_k.append(np.mean(class_n,axis=0))


classes_k=np.array(classes_k)
mean_k=np.array(mean_k)
print(classes_k[0])
print(mean_k[0])

[[ 50  49  50 ... 159 111 117]
 [ 44  50  46 ... 140 104  95]
 [ 46  50  45 ... 136 144  98]
 [ 43  46  43 ...  95 162 197]
 [ 52  39  51 ... 133 138 103]]
[ 47.   46.8  47.  ... 132.6 131.8 122. ]


In [ ]:
#Compute the Scatter within S_K  <d*d>      # SW = sum((classes_k - mean_k)^2 )
#Compute Scatter between matrices  <d*d>   # SB = sum( n_k * (mean_k - mean_overall)^2 )

n_k=classes_k[0].shape[0]  #instances
n_features=classes_k[0].shape[1]   #Dims

SW = np.zeros((n_features, n_features))
SB = np.zeros((n_features, n_features)) 

for tclass,mean in zip(classes_k,mean_k):
  SW+=np.dot(np.array(tclass-mean).T,np.array(tclass-mean))
  SB += n_k * np.dot(np.array(mean-mu).T,np.array(mean-mu))


SW=np.array(SW)
SB=np.array(SB)


print(SW)
print("***********")
print(SB)

[[26080.8 25937.6 24975.2 ...  2705.   2437.4  1459.2]
 [25937.6 28734.8 26499.2 ...  3601.   4470.8  4152. ]
 [24975.2 26499.2 27484.4 ...  4411.8  4266.   4166.6]
 ...
 [ 2705.   3601.   4411.8 ... 86285.2 51893.4 46375.6]
 [ 2437.4  4470.8  4266.  ... 51893.4 75846.8 70793. ]
 [ 1459.2  4152.   4166.6 ... 46375.6 70793.  91202.4]]
***********
[[2.03989307e+09 2.03989307e+09 2.03989307e+09 ... 2.03989307e+09
  2.03989307e+09 2.03989307e+09]
 [2.03989307e+09 2.03989307e+09 2.03989307e+09 ... 2.03989307e+09
  2.03989307e+09 2.03989307e+09]
 [2.03989307e+09 2.03989307e+09 2.03989307e+09 ... 2.03989307e+09
  2.03989307e+09 2.03989307e+09]
 ...
 [2.03989307e+09 2.03989307e+09 2.03989307e+09 ... 2.03989307e+09
  2.03989307e+09 2.03989307e+09]
 [2.03989307e+09 2.03989307e+09 2.03989307e+09 ... 2.03989307e+09
  2.03989307e+09 2.03989307e+09]
 [2.03989307e+09 2.03989307e+09 2.03989307e+09 ... 2.03989307e+09
  2.03989307e+09 2.03989307e+09]]


In [ ]:

#Compute the Eigenvalues and Eigenvectors of S^-1 B
eigval, eigvec = np.linalg.eig(np.dot(np.linalg.inv(SW),SB))
print(np.diag(eigval))
print("*****************")
print(eigvec)
print("*********")

[[-8.47163025e+21+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j ...  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j -8.03407360e+08+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j ...  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
  -5.15338984e+07+9.12096044e+07j ...  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]
 ...
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j ...  9.46743942e+00+1.41638282e+01j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j ...  0.00000000e+00+0.00000000e+00j
   9.46743942e+00-1.41638282e+01j  0.00000000e+

In [ ]:
# sort eigenvalues high to low
eigvec = eigvec.T
idxs = np.argsort(abs(eigval))[::-1]
eigval = eigval[idxs]
eigvec = eigvec[idxs]

In [ ]:
# store first 39 eigenvectors <39*10304> projection matrix
U = eigvec[0:39] 

In [ ]:
# project data
#Train data 
train_projected_data=np.dot(trainData, U.T)

#Test data
test_projected_data=np.dot(testData, U.T)

print(projected_data.shape[1] )  #Dims
print(projected_data[0].shape[0])

NameError: ignored

In [19]:
# Classification using KNN
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier


def KNN_classifier(n_neighbors , train_data,trainLabels,test_data):
  #Feature Scaling 
  scaler = StandardScaler()
  scaler.fit(train_projected_data.real)
  X_train = scaler.transform(train_data.real)
  X_test = scaler.transform(test_data.real)

  #Classification
  classifier_1 = KNeighborsClassifier(n_neighbors)
  classifier_1.fit(X_train, trainLabels)
  predeted_labels = classifier_1.predict(X_test)
  return predeted_labels

In [ ]:

#Apply different K valuse 
#Knn=1
pred_1=KNN_classifier(1,train_projected_data,trainLabels,test_projected_data)

#Knn=3
pred_3=KNN_classifier(3,train_projected_data,trainLabels,test_projected_data)

#Knn=5
pred_5=KNN_classifier(5,train_projected_data,trainLabels,test_projected_data)

#Knn=7
pred_7=KNN_classifier(7,train_projected_data,trainLabels,test_projected_data)

# Calculate Accuracy 
from sklearn.metrics import accuracy_score
acc_1 = accuracy_score(testLabels, pred_1)
acc_3 = accuracy_score(testLabels, pred_3)
acc_5 = accuracy_score(testLabels, pred_5)
acc_7 = accuracy_score(testLabels, pred_7)
print(acc_1,acc_3,acc_5,acc_7)

In [ ]:
# Plot the performance measure against the K value
import matplotlib.pyplot as plt
  
# x axis values
x = [1,3,5,7]

# corresponding y axis values
y = [acc_1,acc_3,acc_5,acc_7]

# plotting the points 
plt.plot(x, y)
  
# naming the x axis
plt.xlabel('K value')

# naming the y axis
plt.ylabel('performance measure (accuracy)')

# giving a title to my graph
plt.title('LDA')
  
# function to show the plot
plt.show()

In [ ]:
import matplotlib.pyplot as plt 
import numpy as np 
projected_data[0].reshape(1,39)
plt.imshow(np.array(projected_data[10].reshape(3,13).real), cmap="gray") 
plt.show()


In [ ]:
BASE = '/content/drive/MyDrive/ssp/8th/contours/'
filepaths = [] # Contains the absolute paths of all the image files
for ns_i in os.listdir(BASE): # The folders containing the files are labelled as s1, s2, etc
            filepaths.append(BASE + '/' + ns_i )

In [ ]:
images = []

for filepath in filepaths:
    img= cv2.imread(filepath, 0)
    print(img.size)
    print(img)
    resized_image = img.resize((92,112))
    print(resized_image.size)

images = np.array(images)
images.shape

262144
[[20 18 12 ... 57 66 68]
 [29 28 22 ... 47 57 61]
 [44 44 38 ... 37 49 59]
 ...
 [51 47 47 ... 71 70 60]
 [54 48 44 ... 70 69 60]
 [59 53 46 ... 68 69 60]]


AttributeError: ignored

NameError: ignored



# LDA on Function

In [2]:

def LDA(trainData,testData,samp_class,samp_num):
  
  #calculate over all mean
  mu = np.mean(trainData,axis=0)
  print(mu)

  #calculate over all mean

  #seperate each class and copmute each mean 
  classes_k = [] #2d arrray 40p*5i
  mean_k = [] #2d arrray 40p*1

  for i in range (0,samp_num,samp_class): #40 person
    class_n = trainData[i:i+samp_class, :]
    classes_k.append(class_n)
    mean_k.append(np.mean(class_n,axis=0))


  classes_k=np.array(classes_k)
  mean_k=np.array(mean_k)


  #*******************************
  #Compute the Scatter within S_K  <d*d>      # SW = sum((classes_k - mean_k)^2 )
  #Compute Scatter between matrices  <d*d>   # SB = sum( n_k * (mean_k - mean_overall)^2 )

  n_k=classes_k[0].shape[0]  #instances
  n_features=classes_k[0].shape[1]   #Dims

  SW = np.zeros((n_features, n_features))
  SB = np.zeros((n_features, n_features)) 

  for tclass,mean in zip(classes_k,mean_k):
    SW+=np.dot(np.array(tclass-mean).T,np.array(tclass-mean))
    SB += n_k * np.dot(np.array(mean-mu).T,np.array(mean-mu))


  SW=np.array(SW)
  SB=np.array(SB)


  print("this is SW",SW)
  print("\n***********")
  print("\nthis is SW\n",SB)

  #Compute the Eigenvalues and Eigenvectors of S^-1 B
  eigval, eigvec = np.linalg.eig(np.dot(np.linalg.inv(SW),SB))
  print("eigvalues : \n",np.diag(eigval))
  print("*****************")
  print("eigvalues : \n:",eigvec)
  print("*********")

  # sort eigenvalues high to low
  eigvec = eigvec.T
  idxs = np.argsort(abs(eigval))[::-1]
  eigval = eigval[idxs]
  eigvec = eigvec[idxs]

  # store first 39 eigenvectors <39*10304> projection matrix
  U = eigvec[0:39] 

  #project data
  #Train data 
  train_projected_data=np.dot(trainData, U.T)

  #Test data
  test_projected_data=np.dot(testData, U.T)


  return train_projected_data,test_projected_data


In [ ]:
train_projected_data,test_projected_data = LDA(trainData,testData,5,200)
train_projected_data,test_projected_data

[86.18  86.295 86.36  ... 78.28  77.145 76.34 ]
[[44 48 45 ... 33 36 37]
 [45 49 47 ... 40 30 44]
 [52 48 47 ... 32 31 37]
 [48 44 49 ... 38 35 44]
 [48 46 49 ... 31 31 36]]
[47.4 47.  47.4 ... 34.8 32.6 39.6]
[[ 26766.4  26484.4  26050.4 ...    730.    4457.    5166.8]
 [ 26484.4  28797.6  27262.2 ...   2217.2   5329.6   5983. ]
 [ 26050.4  27262.2  28228.8 ...   1299.    5072.8   6833. ]
 ...
 [   730.    2217.2   1299.  ... 108602.4  61913.6  46048.4]
 [  4457.    5329.6   5072.8 ...  61913.6  75330.8  67798. ]
 [  5166.8   5983.    6833.  ...  46048.4  67798.   85759.6]]
***********
[[2.07998141e+09 2.07998141e+09 2.07998141e+09 ... 2.07998141e+09
  2.07998141e+09 2.07998141e+09]
 [2.07998141e+09 2.07998141e+09 2.07998141e+09 ... 2.07998141e+09
  2.07998141e+09 2.07998141e+09]
 [2.07998141e+09 2.07998141e+09 2.07998141e+09 ... 2.07998141e+09
  2.07998141e+09 2.07998141e+09]
 ...
 [2.07998141e+09 2.07998141e+09 2.07998141e+09 ... 2.07998141e+09
  2.07998141e+09 2.07998141e+09]
 [2.0

(array([[ 51.66988979 +0.j        , -37.9986272  -0.27892984j,
         -37.9986272  +0.27892984j, ..., -59.03823663 +0.83705871j,
          -9.0243842 -40.55017837j,  -9.0243842 +40.55017837j],
        [ 51.66988979 +0.j        , -48.29821614 +0.43985142j,
         -48.29821614 -0.43985142j, ..., -38.92229935 +8.87973481j,
          -1.43293034-21.25245225j,  -1.43293034+21.25245225j],
        [ 51.66988979 +0.j        , -42.3920131  -0.47591718j,
         -42.3920131  +0.47591718j, ..., -31.11993851+20.86051202j,
           6.53316499-44.42858662j,   6.53316499+44.42858662j],
        ...,
        [ 70.64389632 +0.j        , -40.15967988 -5.02556393j,
         -40.15967988 +5.02556393j, ..., -36.71944007+48.56278269j,
          36.67173404-14.9447198j ,  36.67173404+14.9447198j ],
        [ 70.64389632 +0.j        , -47.48926669 -4.7084708j ,
         -47.48926669 +4.7084708j , ..., -38.50908544+38.390559j  ,
          21.02377567-36.42806109j,  21.02377567+36.42806109j],
        [ 70



# **Compare vs Non-Face Images**

**Read *Non faces* Data**

In [9]:
# read the contour data set 
filepaths_nonface = [] # Contains the absolute paths of all the image files
BASE = '/content/drive/MyDrive/ssp/8th/contours/'
for ns_i in os.listdir(BASE): # The folders containing the files are labelled as s1, s2, etc
            filepaths_nonface .append(BASE + '/' + ns_i )

**Resize to 92x112.**

In [10]:
from PIL import Image
import matplotlib.pyplot as plt 
resized_images = []

for filepath in filepaths_nonface:
    #img= cv2.imread(filepath, 0)
    img = Image.open(filepath)
    resized_image = np.array( img.resize((92,112)) )
    resized_images.append(resized_image)

#print image 
'''
print(resized_images[0])
plt.imshow(resized_images[0], cmap="gray") 
plt.show()
'''

'\nprint(resized_images[0])\nplt.imshow(resized_images[0], cmap="gray") \nplt.show()\n'

**Read *Faces* dataset**

In [11]:
BASE = '/content/drive/MyDrive/ssp/8th/ORL_DataSet/'
filepaths_face = [] # Contains the absolute paths of all the image files
for s_i in os.listdir(BASE): # The folders containing the files are labelled as s1, s2, etc
    if s_i != 'README': # There is also a README file present in the data, this must be ignored
        for filename in os.listdir(BASE + s_i):
            filepaths_face.append(BASE + s_i + '/' + filename)

**Merge to datasets ( Faces & non faces )**

In [48]:
images = [] # the data set contains faces and non faces <440,10304>
#add Faces imgs
for filepath in filepaths_face:
    images.append(cv2.imread(filepath, 0).flatten())
images = images[0:40]
#add Non Faces imgs
for nonFaceImg in resized_images :
    images.append(nonFaceImg.flatten())

images = np.array(images)
images.shape


(80, 10304)

**Add Labels ('1' faces , '0' non faces')**


*  40 faces img
*  40 non faces img




In [50]:
labels = []
# faces 
for i in range (40): 
    labels.append(1)

#non faces 
for i in range (40): 
    labels.append(0)

labels = np.array(labels)
print(labels)


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0]


**Split The data set ( train & test )**

In [51]:
trainData = []
testData = []
trainLabels = []
testLabels = []
count =0 
for image,label in zip(images,labels):
  if count % 2 == 1:
    trainData.append(image)
    trainLabels.append(label)
  else:
    testData.append(image)
    testLabels.append(label)
  count += 1 
trainData = np.array(trainData) 
testData = np.array(testData)
trainLabels = np.array(trainLabels) 
testLabels = np.array(testLabels)

Print the data 

In [52]:
i=0

for i, image in enumerate(images):
  print(labels[i],image.shape,"  ",image) 
print("-------------------------------------------------------------------------------------------------")
i=0


for trainImg in (trainData):
  print(trainImg)
#  print(trainLabels[i])
print("-------------------------------------------------------------------------------------------------")

for testImg   in (testData):
  print(testImg)  
 # print(testLabels[i])

1 (10304,)    [ 41  42  47 ... 141 156 149]
1 (10304,)    [ 50  49  50 ... 159 111 117]
1 (10304,)    [ 44  44  47 ... 188 165 106]
1 (10304,)    [ 44  50  46 ... 140 104  95]
1 (10304,)    [ 51  46  48 ... 196 173 110]
1 (10304,)    [ 46  50  45 ... 136 144  98]
1 (10304,)    [ 47  46  46 ... 151 143  90]
1 (10304,)    [ 43  46  43 ...  95 162 197]
1 (10304,)    [ 44  48  51 ... 129 131 125]
1 (10304,)    [ 52  39  51 ... 133 138 103]
1 (10304,)    [104 101 105 ...  49  43  36]
1 (10304,)    [114 109 112 ...  37  35  38]
1 (10304,)    [111 110 111 ...  35  40  29]
1 (10304,)    [111 106 106 ...  43  34  43]
1 (10304,)    [100 105 103 ...  41  37  37]
1 (10304,)    [106 105 106 ...  32  31  28]
1 (10304,)    [106 110 107 ...  44  49  31]
1 (10304,)    [107 108 107 ...  28  39  43]
1 (10304,)    [ 95 101  99 ...  40  42  53]
1 (10304,)    [105 104 104 ...  43  41  24]
1 (10304,)    [117 120 122 ...  66  59  65]
1 (10304,)    [121 119 121 ...  83  80  86]
1 (10304,)    [121 120 122 ...  

In [53]:
train_projected_data,test_projected_data = LDA(trainData,testData,20,40)
train_projected_data,test_projected_data

[89.325 91.325 93.325 ... 89.325 89.975 89.325]
this is SW [[111604.75 110067.35 108603.15 ...  -2991.    -1692.4     953.  ]
 [110067.35 111753.55 111299.15 ...  -5234.4   -1808.     3340.6 ]
 [108603.15 111299.15 115097.15 ...  -7425.6   -3135.8    3128.4 ]
 ...
 [ -2991.    -5234.4   -7425.6  ...  61904.75  55077.85  47651.75]
 [ -1692.4   -1808.    -3135.8  ...  55077.85  62419.95  58859.85]
 [   953.     3340.6    3128.4  ...  47651.75  58859.85  66410.75]]

***********

this is SW
 [[1.7082495e+08 1.7082495e+08 1.7082495e+08 ... 1.7082495e+08
  1.7082495e+08 1.7082495e+08]
 [1.7082495e+08 1.7082495e+08 1.7082495e+08 ... 1.7082495e+08
  1.7082495e+08 1.7082495e+08]
 [1.7082495e+08 1.7082495e+08 1.7082495e+08 ... 1.7082495e+08
  1.7082495e+08 1.7082495e+08]
 ...
 [1.7082495e+08 1.7082495e+08 1.7082495e+08 ... 1.7082495e+08
  1.7082495e+08 1.7082495e+08]
 [1.7082495e+08 1.7082495e+08 1.7082495e+08 ... 1.7082495e+08
  1.7082495e+08 1.7082495e+08]
 [1.7082495e+08 1.7082495e+08 1.70824

(array([[ 43.07128584 +0.j        ,  22.06677333 +0.j        ,
         -31.65190025 +0.j        , ...,   7.65319561+11.62420544j,
           7.65319561-11.62420544j, -41.28634346 +0.j        ],
        [ 43.07128584 +0.j        ,  15.0121763  +0.j        ,
         -14.65422979 +0.j        , ...,  -8.09442093 -2.49706229j,
          -8.09442093 +2.49706229j, -51.95541649 +0.j        ],
        [ 43.07128584 +0.j        ,  21.11195747 +0.j        ,
          23.33624796 +0.j        , ...,   2.96381612 +0.79817401j,
           2.96381612 -0.79817401j, -20.74299471 +0.j        ],
        ...,
        [ 23.2524327  +0.j        , -10.63874964 +0.j        ,
          16.3629545  +0.j        , ...,   6.39156981-35.1589718j ,
           6.39156981+35.1589718j ,  70.92992033 +0.j        ],
        [ 23.2524327  +0.j        ,   6.32603299 +0.j        ,
         -58.57676503 +0.j        , ..., -25.08844698-12.55257518j,
         -25.08844698+12.55257518j,  10.43747777 +0.j        ],
        [ 23

In [54]:
train_projected_data.shape
test_projected_data.shape

(40, 39)

**i. Show failure and success cases.**

In [63]:
#Apply different K valuse 
#Knn=1
pred_1=KNN_classifier(1,train_projected_data,trainLabels,test_projected_data)
success = []
sConut=0
failure = []
fConut=0
for i, label in enumerate(pred_1):
  if label == testLabels[i]:
    str = "img" , i 
    sConut+=1
    success.append(str)
  else :
    str = "img" , i 
    failure.append(str)
    fConut+=1
# Failuire Cases
print("success Cases : ",sConut,"cases")
print(success)
print()

print("Failure Cases : ",fConut,"cases")
print(failure)
print()

# Calculate Accuracy 
from sklearn.metrics import accuracy_score
acc_1 = accuracy_score(testLabels, pred_1)
acc_1

success Cases :  37 cases
[('img', 0), ('img', 1), ('img', 2), ('img', 3), ('img', 4), ('img', 5), ('img', 6), ('img', 7), ('img', 8), ('img', 9), ('img', 10), ('img', 11), ('img', 12), ('img', 13), ('img', 14), ('img', 15), ('img', 16), ('img', 17), ('img', 18), ('img', 19), ('img', 20), ('img', 21), ('img', 22), ('img', 23), ('img', 25), ('img', 26), ('img', 27), ('img', 28), ('img', 29), ('img', 30), ('img', 32), ('img', 33), ('img', 34), ('img', 36), ('img', 37), ('img', 38), ('img', 39)]

Failure Cases :  3 cases
[('img', 24), ('img', 31), ('img', 35)]



0.925

In [31]:
#Apply different K valuse 
#Knn=1
pred_1=KNN_classifier(1,train_projected_data,trainLabels,test_projected_data)

#Knn=3
pred_3=KNN_classifier(3,train_projected_data,trainLabels,test_projected_data)

#Knn=5
pred_5=KNN_classifier(5,train_projected_data,trainLabels,test_projected_data)

#Knn=7
pred_7=KNN_classifier(7,train_projected_data,trainLabels,test_projected_data)

print(pred_1)
# Calculate Accuracy 
from sklearn.metrics import accuracy_score
acc_1 = accuracy_score(testLabels, pred_1)
acc_1

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1]


0.95

In [22]:

# Calculate Accuracy 
from sklearn.metrics import accuracy_score
acc_1 = accuracy_score(testLabels, pred_1)
acc_3 = accuracy_score(testLabels, pred_3)
acc_5 = accuracy_score(testLabels, pred_5)
acc_7 = accuracy_score(testLabels, pred_7)
print(acc_1,acc_3,acc_5,acc_7)

0.95 0.9454545454545454 0.9409090909090909 0.9409090909090909
