<a href="https://colab.research.google.com/github/habiib1999/Face-Recognition/blob/main/Main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data read and Split [Abdul rahman Habib]

In [10]:
import numpy as np
import pandas as pd
%matplotlib inline
from matplotlib import pyplot as plt
import cv2
import os, sys


In [11]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [12]:
BASE = '/content/drive/MyDrive/att-database-of-faces/'
filepaths = [] # Contains the absolute paths of all the image files
for s_i in os.listdir(BASE): # The folders containing the files are labelled as s1, s2, etc
    if s_i != 'README': # There is also a README file present in the data, this must be ignored
        for filename in os.listdir(BASE + s_i):
            filepaths.append(BASE + s_i + '/' + filename)

In [13]:
images = []
for filepath in filepaths:
    images.append(cv2.imread(filepath, 0).flatten())
images = np.array(images)

In [14]:
labels = []
for i in range (40): #40 person
  for j in range(10): #images
    labels.append(i+1)
labels_arr = np.array(labels)
print(labels_arr)


[ 1  1  1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  2  2  2  3  3  3  3
  3  3  3  3  3  3  4  4  4  4  4  4  4  4  4  4  5  5  5  5  5  5  5  5
  5  5  6  6  6  6  6  6  6  6  6  6  7  7  7  7  7  7  7  7  7  7  8  8
  8  8  8  8  8  8  8  8  9  9  9  9  9  9  9  9  9  9 10 10 10 10 10 10
 10 10 10 10 11 11 11 11 11 11 11 11 11 11 12 12 12 12 12 12 12 12 12 12
 13 13 13 13 13 13 13 13 13 13 14 14 14 14 14 14 14 14 14 14 15 15 15 15
 15 15 15 15 15 15 16 16 16 16 16 16 16 16 16 16 17 17 17 17 17 17 17 17
 17 17 18 18 18 18 18 18 18 18 18 18 19 19 19 19 19 19 19 19 19 19 20 20
 20 20 20 20 20 20 20 20 21 21 21 21 21 21 21 21 21 21 22 22 22 22 22 22
 22 22 22 22 23 23 23 23 23 23 23 23 23 23 24 24 24 24 24 24 24 24 24 24
 25 25 25 25 25 25 25 25 25 25 26 26 26 26 26 26 26 26 26 26 27 27 27 27
 27 27 27 27 27 27 28 28 28 28 28 28 28 28 28 28 29 29 29 29 29 29 29 29
 29 29 30 30 30 30 30 30 30 30 30 30 31 31 31 31 31 31 31 31 31 31 32 32
 32 32 32 32 32 32 32 32 33 33 33 33 33 33 33 33 33

In [ ]:
trainData = []
testData = []

In [15]:
for image in images:
    print(image)

[128 125 125 ...  45  31  30]
[117 115 115 ...  53  46  68]
[114 115 115 ...  78  85  77]
[117 112 115 ...  82  82  80]
[126 130 131 ...  43  51  48]
[117 114 116 ...  85  89  91]
[116 116 117 ...  83  76  77]
[131 128 126 ...  41  40  35]
[129 127 128 ...  32  35  40]
[117 113 118 ...  78  85  82]
[ 97  94  92 ... 144 143 129]
[ 89  87  92 ...  93 112 109]
[ 88  85  89 ... 117 117 116]
[ 87  93  84 ... 125 117 125]
[ 93  93  88 ... 112 111 111]
[ 75  77  75 ... 116 114 113]
[ 74  74  78 ... 109 113 120]
[ 74  74  76 ... 135 127 118]
[ 86  90  87 ... 127 124 126]
[ 83  86  84 ... 136 138 134]
[104 106 107 ...  65  59  73]
[106 104 104 ...  74  66  68]
[105 109 105 ...  81  57  49]
[108 112 109 ...  73  64  69]
[108 105 104 ...  72  73  48]
[113 109 113 ...  72  66  71]
[103 109 105 ...  53  58  54]
[109 112 114 ...  69  72  69]
[114 112 110 ...  67  70  68]
[110 111 114 ...  65  72  65]
[110 109 111 ...  94  88  90]
[110 112 113 ...  92  87  90]
[105 102 106 ...  72  62  75]
[111 111 1

# LDA [Mohammed Aiman]

# PCA [Ahmed Ashraf]