<a href="https://colab.research.google.com/github/habiib1999/Face-Recognition/blob/main/Main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data read and Split [Abdul rahman Habib]

In [5]:
import numpy as np
import pandas as pd
%matplotlib inline
from matplotlib import pyplot as plt
import cv2
import os, sys


In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
BASE = '/content/drive/MyDrive/att-database-of-faces/'
filepaths = [] # Contains the absolute paths of all the image files
for s_i in os.listdir(BASE): # The folders containing the files are labelled as s1, s2, etc
    if s_i != 'README': # There is also a README file present in the data, this must be ignored
        for filename in os.listdir(BASE + s_i):
            filepaths.append(BASE + s_i + '/' + filename)

In [8]:
images = []
for filepath in filepaths:
    images.append(cv2.imread(filepath, 0).flatten())
images = np.array(images)

In [ ]:
labels = []
for i in range (40): #40 person
  for j in range(10): #images
    labels.append(i+1)
labels = np.array(labels)
print(labels)


In [10]:
trainData = []
testData = []
trainLabels = []
testLabels = []
count = 0
for image,label in zip(images,labels):
  if count % 2 == 1:
    trainData.append(image)
    trainLabels.append(label)
  else:
    testData.append(image)
    testLabels.append(label)
  count += 1 
trainData = np.array(trainData) 
testData = np.array(testData)
trainLabels = np.array(trainLabels) 
testLabels = np.array(testLabels)

In [ ]:
for image in images:
  print(image)
  print("-------------------------------------------------------------------------------------------------")
for trainImg in trainData:
  print(trainImg)
for testImg in testData:
  print(testImg)   

# PCA [Ahmed Ashraf]

a. Use the pseudo code below for computing the projection matrix U. 
Define the alpha = {0.8,0.85,0.9,0.95}


In [12]:
mean=np.array([np.mean(images, axis=0)])
mean

array([[85.6175, 85.5775, 85.925 , ..., 76.87  , 75.865 , 75.2275]])

In [13]:
centered=images-mean
centered

array([[-43.6175, -44.5775, -41.925 , ..., -34.87  , -32.865 , -34.2275],
       [-41.6175, -42.5775, -53.925 , ..., -33.87  , -32.865 , -38.2275],
       [-44.6175, -38.5775, -38.925 , ..., -41.87  , -38.865 , -37.2275],
       ...,
       [ 11.3825,  19.4225,  21.075 , ...,  -0.87  ,  -8.865 ,  -1.2275],
       [ 19.3825,  16.4225,  20.075 , ...,  -4.87  , -13.865 ,  -0.2275],
       [ 14.3825,  24.4225,  21.075 , ..., -12.87  ,  -4.865 , -16.2275]])

In [14]:
cov=np.cov(centered.T)
cov

array([[1283.65031955, 1271.88059524, 1266.10407268, ..., -153.3506015 ,
        -112.43522556,  -58.93531955],
       [1271.88059524, 1276.58044486, 1263.86296992, ..., -150.44854637,
        -110.82660401,  -58.63296366],
       [1266.10407268, 1263.86296992, 1267.87406015, ..., -148.6914787 ,
        -105.79461153,  -57.20093985],
       ...,
       [-153.3506015 , -150.44854637, -148.6914787 , ..., 2205.1760401 ,
        1934.52626566, 1786.40809524],
       [-112.43522556, -110.82660401, -105.79461153, ..., 1934.52626566,
        1978.60328321, 1841.77765664],
       [ -58.93531955,  -58.63296366,  -57.20093985, ..., 1786.40809524,
        1841.77765664, 1937.10350251]])

In [15]:
from numpy import linalg 
w,v= np.linalg.eig(cov)
eigenvalues= np.array(w)
eigenvectors=np.array(v)
print("eigenvalues= \n",eigenvalues)
print("eigenvectors= \n",eigenvectors)

eigenvalues= 
 [ 2.82391006e+06+0.00000000e+00j  2.06973946e+06+0.00000000e+00j
  1.09704614e+06+0.00000000e+00j ... -6.89275480e-13-1.61908658e-13j
 -7.18725954e-13+6.55052398e-14j -7.18725954e-13-6.55052398e-14j]
eigenvectors= 
 [[-2.12507923e-03+0.00000000e+00j  1.46851506e-02+0.00000000e+00j
   1.99294881e-02+0.00000000e+00j ... -1.09212964e-03+2.84120306e-04j
  -1.54447550e-03-3.95050650e-04j -1.54447550e-03+3.95050650e-04j]
 [-2.11276614e-03+0.00000000e+00j  1.46139383e-02+0.00000000e+00j
   2.00092007e-02+0.00000000e+00j ... -1.51172088e-08+3.29736997e-05j
  -4.38998493e-06-3.03879702e-05j -4.38998493e-06+3.03879702e-05j]
 [-2.14250419e-03+0.00000000e+00j  1.46318643e-02+0.00000000e+00j
   1.98385174e-02+0.00000000e+00j ... -3.30125039e-05-2.29295351e-05j
  -4.20338608e-05-1.45662427e-05j -4.20338608e-05+1.45662427e-05j]
 ...
 [-7.04005567e-03+0.00000000e+00j -1.05610380e-02+0.00000000e+00j
   1.41636829e-02+0.00000000e+00j ... -9.25680092e-03+2.31840238e-03j
  -1.01258522e-02-7

In [19]:
 # Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eigenvalues[i]), eigenvectors[:,i]) for i in range(len(eigenvalues))]
# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort(key=lambda x: x[0], reverse=True)
# Visually confirm that the list is correctly sorted by decreasing eigenvalues
print('Eigenvalues in descending order:')
print(f"Q3.g -> eigen pairs value & vector ordered:\n{eig_pairs}\n")

Streaming output truncated to the last 5000 lines.
       -7.09918636e-05+4.22709217e-08j, ...,
       -1.16807589e-03-9.16266265e-03j,  2.00282516e-04+8.51446723e-04j,
       -9.20310228e-04+5.97243705e-03j])), (4.265296973117466e-12, array([-6.96811285e-04-9.04145450e-04j, -9.61668713e-05-2.18096773e-05j,
       -9.44658949e-06+2.76415095e-05j, ...,
        2.79344521e-03-1.34181187e-02j, -2.87232028e-03+5.38730552e-03j,
        2.41476067e-03-3.06360447e-03j])), (4.265296973117466e-12, array([-6.96811285e-04+9.04145450e-04j, -9.61668713e-05+2.18096773e-05j,
       -9.44658949e-06-2.76415095e-05j, ...,
        2.79344521e-03+1.34181187e-02j, -2.87232028e-03-5.38730552e-03j,
        2.41476067e-03+3.06360447e-03j])), (4.261007990322515e-12, array([-2.80292354e-04-7.75427110e-04j, -9.95111419e-06+4.84899911e-06j,
       -1.43236500e-05-9.27049002e-05j, ...,
        1.26623336e-03-4.93615054e-03j, -3.10882071e-03+8.29680187e-03j,
        5.49834612e-03-7.97167798e-03j])), (4.26100799032

In [23]:
 # Q3.h
tot = sum(eigenvalues)
explainedVriance = [(i / tot)*100 for i in sorted(eigenvalues, reverse=True)]
print(f"Q3.h -> Explained variance:\n{explainedVriance}\n") #we will take pc1 and pc2

print(sum(explainedVriance))

Q3.h -> Explained variance:
[(17.609549780232605+0j), (12.906636270754587+0j), (6.841042453498397+0j), (5.5789428433485915+0j), (5.109912685183243+0j), (3.3625336689517593+0j), (2.4471967498269525+0j), (2.331064364864164+0j), (1.9622021784230559+0j), (1.8027805384675162+0j), (1.4389234248627651+0j), (1.3979224444748481+0j), (1.1190403195665115+0j), (1.0672741075801155+0j), (0.9746471624560261+0j), (0.9136254290709701+0j), (0.8760419529135459+0j), (0.8444523749274769+0j), (0.735490639301345+0j), (0.6953673669735065+0j), (0.6709465761241068+0j), (0.6385096951392233+0j), (0.593075539357846+0j), (0.5437966318542218+0j), (0.5290913775924577+0j), (0.493587233011845+0j), (0.48133201230993927+0j), (0.4788858546192438+0j), (0.44802625379080335+0j), (0.4361400922456223+0j), (0.42907558279169894+0j), (0.39916654438835175+0j), (0.3945011637486059+0j), (0.3803087568888808+0j), (0.36953627486679735+0j), (0.3503700944442145+0j), (0.3399971815239965+0j), (0.33642576099171057+0j), (0.31737927257224924+

In [22]:
variance_explained = []
for i in eigenvalues:
     variance_explained.append((i/sum(eigenvalues))*100)


sum_explained=sum(variance_explained)
print(variance_explained)    
print(sum_explained) 

[(17.609549780232605+0j), (12.906636270754587+0j), (6.841042453498397+0j), (5.5789428433485915+0j), (5.109912685183243+0j), (3.3625336689517593+0j), (2.4471967498269525+0j), (2.331064364864164+0j), (1.9622021784230559+0j), (1.8027805384675162+0j), (1.4389234248627651+0j), (1.3979224444748481+0j), (1.1190403195665115+0j), (1.0672741075801155+0j), (0.9746471624560261+0j), (0.9136254290709701+0j), (0.8760419529135459+0j), (0.8444523749274769+0j), (0.735490639301345+0j), (0.6953673669735065+0j), (0.6709465761241068+0j), (0.6385096951392233+0j), (0.593075539357846+0j), (0.5437966318542218+0j), (0.5290913775924577+0j), (0.493587233011845+0j), (0.48133201230993927+0j), (0.4788858546192438+0j), (0.44802625379080335+0j), (0.4361400922456223+0j), (0.42907558279169894+0j), (0.39916654438835175+0j), (0.3945011637486059+0j), (0.3803087568888808+0j), (0.36953627486679735+0j), (0.3503700944442145+0j), (0.3399971815239965+0j), (0.33642576099171057+0j), (0.31737927257224924+0j), (0.300237271773811+0j),

# LDA [Mohammed Aiman]